barcode = $(barcode)
universe = vanilla
executable = /bin/singularity
arguments = exec -B /lustre/home/enza/ /lustre/home/enza/biocontainers/strique_latest.sif python3 /app/scripts/STRique.py index /lustre/home/enza/cattaneo/20191122_1440_MN29119_FAL40216_99a47f42/fast5_pass/$(barcode)/ 
output = /lustre/home/enza/cattaneo/20191122_1440_MN29119_FAL40216_99a47f42/fast5_pass/$(barcode)/reads.fofn
error = /lustrehome/gianluca/junk/striqueIndex_$(barcode).err
log = /lustrehome/gianluca/junk/striqueIndex_$(barcode).out
request_cpus = 1
rank = Memory
getenv = True
transfer_executable = False
queue
